In [20]:
# Consider a binary matrix A where rows are alignments and columns are sites.
# In this matrix, 1 indicates a nongap (e.g A,C,G,T) and 0 indicates gap (-) character.
# For a randomly chosen pair of alignments what would be expected number of sites where
# both alignments have a non-gap character?
#
# The trivial algorithm is O(mn^2) where n is number of rows and m is number of columns.
# Clever algorithm is O(nm).

In [21]:
import numpy as np


m=2000
n=2000
a=np.zeros((m,n))
print(a)



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
for i in range(m):
    for j in range (n):
        a[i,j] = np.random.randint(2)
print(a)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]]


In [23]:
# this is the brute force approach. First we calculate A*A^T then we average upper triangle elements
# excluding the main diagonal.
def upper_tri_masking(A):
    m = A.shape[0]
    r = np.arange(m)
    mask = r[:,None] < r
    return A[mask]

def average_brute_force(a):
    return np.mean(upper_tri_masking(a.dot(a.transpose())))

average_brute_force(a)

500.42581340670336

In [24]:
%timeit average_brute_force(a)

129 ms ± 1.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
# This is the clever approach. Sum of upper triangle elements excluding the main diagonal is 
# (e^T*A*A^T*e  - Tr(A*A^T))/2 where e is column vector of ones.
def average_clever(a):
    s=np.sum(a, axis=0)
    t=s.dot(s)
    x=sum(s)
    m = a.shape[0]   
    return (t-x)/m/(m-1)

average_clever(a)     

500.42581340670336

In [26]:
%timeit average_clever(a)

2.32 ms ± 231 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
# example

import numpy as np

# mean overlap is 3.4
x = np.array(
    [ [1,1,1,1,0],
      [1,1,1,1,0],
      [1,1,1,1,0],
      [0,1,1,1,1],
      [0,1,1,1,1]
    ])

# mean overlap is 3. in fact every pair or rows exactly have overlap 3.
y = np.array(
    [ [1,1,1,1,0],
      [1,1,1,0,1],
      [1,1,0,1,1],
      [1,0,1,1,1],
      [0,1,1,1,1]
    ])
# mean overlap is 4.
z = np.array(
    [ [1,1,1,1,0],
      [1,1,1,1,0],
      [1,1,1,1,0],
      [1,1,1,1,0],
      [1,1,1,1,0]
    ])
print(average_clever(x))
print(average_clever(y))
print(average_clever(z))

3.4
3.0
4.0
